### PR TITLE
Add files from codepen, Updated stripped_data.json format

### PR DESCRIPTION
**Pull request by miffycs**
- Added files from [codepen](https://codepen.io/fastandlucid/pen/bGQrPwX)
- Updated `stripped_data.json` format to minimize file size
- Modified `script.js` to work with new format in stripped_data
- Updated URL in `script.js` to always pull from origin:main instead of a specific commit
- Added GitHub Actions to run `fetch.js` every 5 minutes which updates `stripped_data.json`

### CODE REVIEW

**Comment by miffycs** [comment]
To enable GitHub Actions which automatically fetches data every 5 minutes, go to [Settings > Actions](https://github.com/fastandlucid/assets/settings/actions) and give read and write permission under Workflow Permissions (see below):

41320338-b6add587bb158f21ad79c3275e8d3579

-----

(Optional)
Also enable [Settings > Pages](https://github.com/fastandlucid/assets/settings/pages), configure Source, Branch, Enforce HTTPS as below: 
Pages

This should generate a free website for you with an URL similar to `https://fastandlucid.github.io/assets/` and allow the website to be accessed publicly. After this is properly configured and deployed, you should see the assigned URL.

**Comment by fastandlucid** [comment]
Thanks for all this @miffycs I've merged and configured both those things! How do we deploy?

**Comment by miffycs** [comment]
Deploys should happen automatically with each push/merge. I see we are live :)
https://fastandlucid.github.io/assets/

**Comment by fastandlucid** [comment]
Oh, awesome!  Thanks. So cool to see. And I guess it's relatively straightforward to move to a custom domain at some point if that's necessary?

**Comment by miffycs** [comment]
Yup! Github pages defaults to {username}.github.io/{repo_name} so you can change the repo name to something else, or wait till we have a dedicated domain name (prob just move under devzuki)

**Pull request merged**
